import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import { Navbar } from './components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <AntdRegistry>
          <ConfigProvider theme={{
            token: {
              fontFamily: 'Lato'
            }
          }}>
            <div className="p-4 flex justify-center">{children}</div>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
